### ISSUE TITLE
Compiling on Power9

### ISSUE THREAD

**Issue by aprokop** [wangyiqiu/dbscan#1]
I'm interested in running some experiments with this code on [OLCF Summit](https://docs.olcf.ornl.gov/systems/summit_user_guide.html), which has IBM Power9 CPUs. I've been unsuccessful in the compilation so far.

I've installed jemalloc using [Spack](https://github.com/spack/spack). After loading it, and running
```
make clean; GCILK=1 USE_JEMALLOC=1 make -j;
```
I'm getting 
```
g++: error: unrecognized command-line option '-mcx16'
```
This is with GCC 10.2.0. If I manually disable that flag (can I even do that?)
```diff
--- a/c++/parallelDefs
+++ b/c++/parallelDefs
@@ -26,7 +26,8 @@ PLFLAGS =  -ldl -fcilkplus $(SDSLLF)

 else ifdef GCILK
 PCC = g++
-PCFLAGS = -fcilkplus -mcx16 -O3 -DCILKP -DMCX16 $(INTT) $(SDSLCF) $(EXFLAGS)
+# PCFLAGS = -fcilkplus -mcx16 -O3 -DCILKP -DMCX16 $(INTT) $(SDSLCF) $(EXFLAGS)
+PCFLAGS = -fcilkplus -O3 -DCILKP $(INTT) $(SDSLCF) $(EXFLAGS)
 PLFLAGS = -ldl -fcilkplus $(SDSLLF)

 else ifdef GCILK11
```
I'm getting a different error
```
parallel.h:21:10: fatal error: cilk/cilk.h: No such file or directory
   21 | #include <cilk/cilk.h>
```
I was wondering if you have any suggestions as to how this may be resolved. Note, that I was able to compile it without issues on my personal workstation.

**Comment by aprokop** [comment]
OK, after searching some more, I [found out](https://www.phoronix.com/scan.php?page=news_item&px=Intel-Cilk-Plus-Stripped-In-GCC) that Cilk was deprecated in GCC 7 and removed in 8. So, one cannot use any recent GCC versions. Regarding `mcx16`, this is indeed a feature of `x86_64` architecture, and thus is unavailable on Power9 chips.

@wangyiqiu Given all this info, would the recommended platform to use the code be an Intel/AMD chip (x86_64) with GCC versions 5 to 7? Is it possible to (semi-easily) port it to other platforms?

**Comment by wangyiqiu** [comment]
Hi, thanks for your interest.

Indeed, Cilk is already deprecated in the newer versions of gcc, so that may be why the Cilk runtime library wasn't found when you compiled the program using gcc 10.2.0.

The instruction associated with mcx16 may actually be unused for this program, so if it causes compilation problems, you could try compiling it without the -mcx16 flag.

Yes I would recommend to use an x86_64 machine, with gcc version 7.4, which is what we used to produce the results in our paper. An easy set up would be a fresh copy of Ubuntu 18 on an x86_64 machine, which comes with the right compiler and environment.

Please let me know if you have any other questions.

**Comment by aprokop** [comment]
@wangyiqiu Thanks for the feedback. How critical is Cilk to the code? Is it an absolute requirement, or are there alternative parallel frameworks that you can use?

I'll try to run it on AMD Epyc Rome processors then, and see what happens. Just FYI, one of my goals is to try to compare it with a GPU DBSCAN algorithm we developed.

**Comment by wangyiqiu** [comment]
For this version of the DBSCAN that we tested in our paper, the use of Cilk is critical. On the other hand, we do have a non-Cilk implementation that uses an alternative scheduler. The non-Cilk implementation uses the same algorithm, but may have different performance characteristics.

I think it will be interesting the compare our DBSCAN with the GPU DBSCAN algorithm that you developed. Please let me know if you are able to compile this version (the Cilk version) on your machine with AMD Epyc Rome. If it does not work, I will be happy to assist you to compile the non-Cilk version.

**Comment by aprokop** [comment]
@wangyiqiu I was able to successfully compile and run the code on AMD EPYC 7622. I used gcc 7.5. The results look pretty good. It certainly the fastest CPU code I've seen, and beats most GPU codes. The GPU code we implemented in [ArborX](https://github.com/arborx/ArborX) is a bit faster using a 4 year older hardware, but it's closer than I expected.

There are certainly few things we can learn from this.
![arborx_hacc_eps_minpts5_line](https://user-images.githubusercontent.com/7297887/122130259-5a4baf80-ce05-11eb-9cf4-a31883f94d98.png)
![arborx_hacc_minpts_eps0_042_line](https://user-images.githubusercontent.com/7297887/122130262-5ae44600-ce05-11eb-9493-6d9c18532436.png)

**Comment by wangyiqiu** [comment]
@aprokop 
Thanks for letting me know and sending the plots, glad to know that our code works fine on your machine. If you are writing a paper on your algorithm, I really look forward to reading it.

Just curious -- in your plots, what are the methods being compared, and what is the size and dimension of the data?

**Comment by aprokop** [comment]
>  Thanks for letting me know and sending the plots, glad to know that our code works fine on your machine. If you are writing a paper on your algorithm, I really look forward to reading it.

Sure. Our first draft is [here](https://arxiv.org/abs/2103.05162), which unfortunately got rejected from a conference. We plan to resubmit it to a journal.
Anyway, two of the reviewers mentioned your code, so I wanted to take a look.

> Just curious -- in your plots, what are the methods being compared, and what is the size and dimension of the data?

ArborX and ArborX-DenseBox are the two methods we developed (see the paper). TEPP is the abbreviation of your algorithm (from the title of the paper, Theoretically Efficient and Practical Parallel :)), PDSDBSCAN-S is the shared memory version of the Patwary's algorithm from '12 paper. The problem is the cosmological problem, with about 36 million 3D points. From the scientific point of view, the sweet point for the problem is eps = 0.042, and minpts somewhere in the range [2, 20]. We just sweeped few more values there.

It may make sense to use some of the datasets you used in your paper. I plan to take a look at your reproducibility steps, and download those. I noticed that you used Gao-Tan generator. I tried implementing it too (arborx/ArborX#528), but it seems to produce slightly different clusters from the original paper. I'll take a look at yours to see what they look like.

**Comment by wangyiqiu** [comment]
Thanks for sharing the paper -- it looks interesting. I would be glad to take a detailed read later. I wish you best luck in your journal submission!

The testing setup sounds reasonable from my perspective. It was a bit surprising though, that Patwary's algorithm (PDSDBSCAN) from the '12 paper actually runs faster than our method as shown in your second plot. In our [paper](https://arxiv.org/pdf/1912.06255.pdf), we also tested against the PDSDBSCAN implementation in the shared memory setting, but our result shows that we are way faster in nearly all the cases. My speculation is that it could be due the data set and parameters, which can vary in different use cases.

From my perspective, the [data plots](https://github.com/arborx/ArborX/pull/528) that you shared, from your implementation of Gan and Tao's generator look reasonable. On the other hand, if you are interested in trying out Gan and Tao's data (SS-simden and SS-varden), their data generator is released as part of their pre-compiled binary available [here](https://sites.google.com/view/approxdbscan). You may need to note that, the generator only produces integer values in the range of `[0, 10^5]`.

**Comment by wangyiqiu** [comment]
I will close this for now since the program compiled. Please let me know if you have further questions.
